### ISSUE TITLE
Please credit use of playlists?

### ISSUE THREAD

**Issue by geonsey** [bitsbb01/m3u8_creator#2]
Hey, I don't mind you compiling a list of playlists from some awesome places, but if you will be posting the curated playlist from Free2View TV, can you please issue proper credit in your comments? Our team of developers worked hard on this list and it deserves to be recognized. I recommend something like:
   Free2View TV courtesy of the Free2View TV Project and its team of developers: https://discord.gg/C48WhSTpw7

**Comment by bitsbb01** [comment]
it was meant to have been removed, as theres a lot of things that appear in playlists on iptv...

**Comment by bitsbb01** [comment]
have covid,  but have gone in and removed till i can fix all the extra bits in the playlist.
