### ISSUE TITLE
Using someone else's work

### ISSUE THREAD

**Issue by Powerfader1** [bitsbb01/m3u8_creator#3]
If you feel the need to take someone else's hard work. Then at least be professional enough to give them the credit they are due!

Free2View works hard to provide their work for all to use. At least give them the credit for doing the work you decided was good enough for you to take. Better yet, you should ask before taking!

**Comment by bitsbb01** [comment]
this was meant to be removed due to it messing up the main list, and untill i can fix the main list, i've removed... 
Added all the credits to those that have helped.. normally this is done straight away, but had covid and still got long covid.
