### ISSUE TITLE
Documentation link dead

### ISSUE THREAD

**Issue by northernpowerhouse** [bitsbb01/m3u8_creator#5]
The documentation link in the readme is dead, and can't be found on gh pages.

Documentation would be really useful.

**Comment by Viper911** [comment]
+1 Can we get the EPG file back?

**Comment by bitsbb01** [comment]
which epg?
its always there.. https://github.com/bitsbb01/m3u8_creator/raw/main/epg/epg_ripper_ALL_SOURCES1.xml.gz

**Comment by bitsbb01** [comment]
as for documentation, i took that down, as its explained in the main read me.
https://github.com/bitsbb01/m3u8_creator/blob/main/README.md
